name: jellyfin-sso-test

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-10.11.10}
    container_name: jellyfin-sso-test
    ports:
      - "8096:8096"
    volumes:
      - ./.data/jellyfin/config:/config
      - ./.data/jellyfin/cache:/cache
      - ./.data/jellyfin/media:/media
      - ./.publish:/config/plugins/SSO-Auth
    extra_hosts:
      - "dex.localtest.me:host-gateway"
    restart: unless-stopped

  dex:
    image: ghcr.io/dexidp/dex:${DEX_VERSION:-v2.45.1}
    container_name: dex-sso-test
    ports:
      - "5556:5556"
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    restart: unless-stopped
